force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>San Diego</fullName>
            </value>
            <value>
                <fullName>Houston</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaginationProperty.cls
public with sharing class PaginationProperty {

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> fetchRecords(
        Integer pageSize,
        Integer pageNumber,
        Decimal minPrice,
        Decimal maxPrice,
        String status,
        String furnishing
    ) {
        Integer offsetValue = (pageNumber - 1) * pageSize;

        String baseQuery = 'FROM Property__c WHERE Id != null';

        
        if (minPrice != null) {
            baseQuery += ' AND Rent__c >= :minPrice';
        }
        if (maxPrice != null) {
            baseQuery += ' AND Rent__c <= :maxPrice';
        }
        if (String.isNotBlank(status)) {
            baseQuery += ' AND Status__c = :status';
        }
        if (String.isNotBlank(furnishing)) {
            baseQuery += ' AND Furnishing_Status__c = :furnishing';
        }
        String dataQuery = 'SELECT Id, Name, City__c, State__c, Rent__c, Status__c, Furnishing_Status__c '
                         + baseQuery +
                         ' LIMIT :pageSize OFFSET :offsetValue';

        List<Property__c> propertyList = Database.query(dataQuery);
     
        String countQuery = 'SELECT COUNT() ' + baseQuery;
        Integer totalRecords = Database.countQuery(countQuery);

        Integer totalPages = (Integer)Math.ceil((Decimal)totalRecords / pageSize);

        return new Map<String, Object>{
            'property' => propertyList,
            'totalRecords' => totalRecords,
            'totalPages' => totalPages
        };
    }
}