force-app/main/default/objects/Maintenance_Requests__c/Maintenance_Requests__c.object-meta.xml
<CustomObject>
    <label>Maintenance Requests</label>
    <nameField>
        <label>Maintenance Requests</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintainance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Requests__c/fields/Vendor_Management__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Management</label>
    <referenceTo>Vendor_Management__c</referenceTo>
    <relationshipLabel>Maintainance Requests</relationshipLabel>
    <relationshipName>Maintainance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Management__c/Vendor_Management__c.object-meta.xml
<CustomObject>
    <label>Vendor Management</label>
    <nameField>
        <label>Vendor  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MaintenanceRequestHandler.cls
public class MaintenanceRequestHandler {

    public static void assignVendor(List<Maintenance_Requests__c> newRequests) {

       
        List<Vendor_Management__c> vendorList = [
            SELECT Id FROM Vendor_Management__c
        ];

        if (vendorList.isEmpty()) return;

       
        Map<Id, Integer> loadMap = new Map<Id, Integer>();

        for (AggregateResult ar : [
            SELECT Vendor_Management__c vId, COUNT(Id) cnt
            FROM Maintenance_Requests__c
            WHERE Vendor_Management__c != NULL
            GROUP BY Vendor_Management__c
        ]) {
            loadMap.put(
                (Id) ar.get('vId'),
                (Integer) ar.get('cnt')
            );
        }

       
        for (Maintenance_Requests__c req : newRequests) {

            Id selectedVendor;
            Integer minLoad =999999999;

            for (Vendor_Management__c v : vendorList) {

                Integer load = loadMap.containsKey(v.Id)
                    ? loadMap.get(v.Id)
                    : 0;

                if (load < minLoad) {
                    minLoad = load;
                    selectedVendor = v.Id;
                }
            }

            
            req.Vendor_Management__c = selectedVendor;

           
            loadMap.put(selectedVendor, minLoad + 1);
        }
    }
}